blog/config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts

end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def new 
		@post = Post.new
	end

	def create 
		@post = Post.create(post_params)
		redirect_to @post
	end

	def show
		@post = Post.find_by(id: params[:id])
	end

	def destroy
		@post = Post.find_by(id: params[:id])
		@post.destroy

		redirect_to posts_path
	end

	def edit
		@post = Post.find_by(id: params[:id])
	end

	def update
		@post = Post.find_by(id: params[:id])
		@post.update_attributes(post_params)

		redirect_to @post
	end

	private
	def post_params
		params.require(:post).permit(:title, :author, :content)
	end

  end

blog/app/views/layouts/_form.html.erb
<%= form_for @post, url: {action: 'create'} do |f| %>
<%= f.label :headline %>
<%= f.text_field :headline %>
<br /><br />

<%= f.label :title %>
<%= f.text_field :title %>
<br /><br />

<%= f.label :content %>
<%= f.text_area :content %>
<br /><br />

<%= f.submit %>
<% end %>


<%= link_to 'cancel', posts_path %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

blog/app/views/posts/edit.html.erb
<%= form_for @post, url: {action: 'update'} do |f| %>
<%= f.label :title %>
<%= f.text_field :title, value: @post.title %>
<br /><br />

<%= f.label :author %>
<%= f.text_field :author, value: @post.author %>
<br /><br />

<%= f.label :content %>
<%= f.text_area :content, value: @post.author %>
<br /><br />

<%= f.submit %>
<% end %>
<%= link_to 'cancel', @post %>

<%= form_for @post, url:{action: 'update'} do |f|%>
<%= link_to 'cancel', @post %>
<%= render 'layouts/form' %>
<%= end %>

blog/app/views/posts/index.html.erb
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	
 <h1>Welcome to my blog!</h1>
  <% @posts.each do |post| %>
  <h2><%= link_to post.title, post_path(post) %></h2>
  <h3>by <%= post.author %></h3>
  <%= post.content %>
  <% end %>

<br /><br />

<%= link_to 'Create a new post!', new_post_path %>


<%= link_to 'cancel', @post %>
<%= render 'layouts/form' %>

</body>
</html>

blog/app/views/posts/new.html.erb
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  
<%= form_for @post, url: {action: 'create'} do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<br /><br />

<%= f.label :author%>
<%= f.text_field :author%>
<br /><br />

<%= f.label :content%>
<%= f.text_area :content%>
<br /><br />

  <%= f.submit %>
  <% end %>

<%= link_to 'cancel', posts_path %>

<%= render "layouts/form" %>

</body>
</html>

blog/app/views/posts/show.html.erb
  <html lang="en">
  <head>
  	<meta charset="UTF-8">
  	<title>Document</title>
  </head>
  <body>
  	

<h2> <%= @post.title %></h2>
<h3> by <%= @post.author %></h3>
<%= @post.content %>

<br />
<%= link_to 'back', posts_path %>

<%= link_to 'edit', edit_post_path(@post) %>

<br /><br />
<%= link_to 'delete', @post, method: :delete %>

  </body>
  </html>  